# Generated by Django 3.1.4 on 2020-12-27 21:40

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201227_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, unique=True),
        ),
    ]
